# Generated by Django 5.1.6 on 2025-05-15 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0002_alter_carreview_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreview',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreview_set', to='test_project.car'),
        ),
    ]
