# Generated by Django 5.1.6 on 2025-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0002_car_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
