# Generated by Django 5.1.6 on 2025-05-15 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0003_alter_carreview_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image_path',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='carreview',
            name='author',
        ),
        migrations.AddField(
            model_name='carreview',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carreview',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test_project.car'),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='contents',
            field=models.TextField(default=0),
        ),
    ]
