# Generated by Django 5.1.6 on 2025-05-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0004_alter_car_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image_url',
        ),
    ]
